name: athar
description: "An E-Commerce App For Athar Brand."


publish_to: 'none'



version: 1.0.0+1

environment:
  sdk: ^3.11.5



dependencies:
  flutter:
    sdk: flutter

  dio: ^5.9.0
  hive: ^2.2.3
  intl: ^0.20.2
  get_it: ^9.2.1
  equatable: ^2.0.8
  go_router: ^17.2.3
  google_fonts: ^8.1.0
  hive_flutter: ^1.1.0
  flutter_bloc: ^9.1.1
  image_picker: ^1.2.2
  flutter_animate: ^4.5.2
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^11.0.0
  flutter_secure_storage: ^10.1.0
  firebase_core: ^4.11.0
  firebase_auth: ^6.5.4
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0



flutter_launcher_icons:
  android: true
  image_path: "assets/app_icons/master/alef_final_master.png"
  # Android adaptive icon
  adaptive_icon_background: "#FF020617"
  adaptive_icon_foreground: "assets/app_icons/master/alef_final_master.png"
  # Optional monochrome for Android 13+
  adaptive_icon_monochrome: "assets/app_icons/master/alef_final_master.png"
  min_sdk_android: 21





flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/stickers/
    - assets/images/design/
    - assets/app_icons/master/
    - assets/app_icons/splash/
    - assets/app_icons/android/
